### ISSUE TITLE
Clang crashed while compiling CBaseMath.cpp in Xcode 10.1 Release Mode only

### ISSUE THREAD

**Issue by kechan** [jph00/BaseMath#7]
I placed the .h, .cpp and created the required bridging header to allow the swift-cpp interop and created a project in Xcode. Previously when testing in Debug mode, everything compiled and runtime worked fine, and with minor workaround, all XCTests passed. 

However, when I switched over to Release mode. The project failed to build due to a Clang crash. It is a low level crash with next to no indication to whats wrong (at least to my untrained eye). So I proceeded to comment out a subset of .cpp until it compiled. 

This is the list of math func that caused Clang crash.

abs
sqrt
cos
exp
exp2
log
log10
log2
nearbyint
rint
sin

both float and double. Here's an example:

```
void sm_abs_float(const float* __restrict__ pSrc, float* __restrict__ pDst, const int len) {
  #pragma ivdep
  #pragma clang loop interleave_count(8)
  for (int i=0; i<len; ++i) { pDst[i] = abs(pSrc[i]); }
} 
```

The summation version of these are fine. Only element-wise assignment across the array pointer has problem. Other math func, e.g. tanh, is fine. The func that worked happen to be available in standard swift generic functions, while others only available in the toolchain c++ math.h. I am not sure if this pattern of failure rings any bells? I don't understand this deep enough. 

As for quick workaround, you can comment out 
 
   #pragma clang loop interleave_count(8)

for those that cause problems, and compilation will pass. I absolutely do not know what harm this will do to the library.

**Comment by jph00** [comment]
What if you use AlignedStorage<Double> instead of Array<Double>?

**Comment by jph00** [comment]
I've removed that pragma now so should be fine. Thanks for looking in to this.
